#!/bin/bash

rm -fr build
mkdir build
cd build
cmake .. -DBUILD_PYTHON_BINDINGS=ON
make
cp ~/repos/randSpg/tests/bindingTests/test_pyrandspg.py ~/repos/randSpg/build/python/
nosetests ~/repos/randSpg/build/python/test_pyrandspg.py
